terra_custom_layers = {
    "InstanceNormalization": "normalization_custom_layers",
    "VAEBlock": "gan_custom_layers",
    "YOLOResBlock": "yolo_custom_layers",
    "YOLOv3ResBlock": "yolo_custom_layers",
    "YOLOConvBlock": "yolo_custom_layers",
    "Mish": "normalization_custom_layers",
    "CONVBlock": "base_custom_layers",
    "PSPBlock2D": "base_custom_layers",
    "UNETBlock2D": "base_custom_layers",
    "UNETBlock1D": "base_custom_layers",
    "UNETBlock3D": "base_custom_layers",
    "PSPBlock1D": "base_custom_layers",
    "PretrainedYOLO": "pretrained_custom_layers",
    "ConditionalMergeLayer": "gan_custom_layers",
    "ResnetBlock2D": "base_custom_layers",
    "RGBNormalization": "normalization_custom_layers",
    "VAEDiscriminatorBlock": "gan_custom_layers",
    "PretrainedModel": "pretrained_custom_layers",
}

